# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    # Runs a single command using the runners shell
    - name: Check File Directory
      run: |
        pwd
        ls -al

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "COMPLETE"
        echo ${{ github.ref }}
    #    bash init.sh github
    #    bash cleaning.sh

    - name: Generate changelog
      uses: charmixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit files
      env:
        CI_USER: shdkej
        CI_EMAIL: shdkej@github.com
      run: |
        git config --local user.email "$CI_EMAIL"
        git config --local user.name "$CI_USER"
        git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

    - name: Push changes
      run: |
        git push origin master
