# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    # Runs a single command using the runners shell
    - name: Check File Directory
      run: |
        pwd
        ls -al

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "COMPLETE"
        echo ${{ github.ref }}
    #    bash init.sh github
    #    bash cleaning.sh

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the changelog
      run: echo "${{ steps.changelog.outputs.changelog }}"
