# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: ${{ github.head_ref }}

    # Runs a single command using the runners shell
    - name: Check File Directory
      run: |
        pwd
        ls -al

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "COMPLETE"
        echo "skip"
    #    bash init.sh github
    #    bash cleaning.sh

    - name: Get version from tag
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
        echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Update Changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issues: true
        issuesWoLabels: true
        pullRequests: true
        prWoLabels: true
        addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Changelog for tag ${{ env.CURRENT_VERSION }}
        file_pattern: CHANGELOG.md
