# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Check File Directory
      run: |
        pwd
        ls -al

    - name: Run a multi-line script
      run: |
        echo "COMPLETE"
        echo "skip"
    #    bash init.sh github
    #    bash cleaning.sh

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: changelog-action
      id: generator
      uses: gandarez/changelog-action@v1.0.4
        
    - name: push tag
      run : |
        echo "${{ steps.generator.outputs.new_tag }}"
        echo "${{ steps.generator.outputs.changelog }}" > CHANGELOG.md
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Changelog for PR
        file_pattern: CHANGELOG.md
        branch: master
